'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1008
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SGE_Eventos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _10194() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_10194", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _101941() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_101941", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10239() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_10239", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _102391() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_102391", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Ok_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Ok_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _16__Ok_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_16__Ok_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _print1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_print1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _print2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_print2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property almacen22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almacen22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property almacen24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almacen24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property applications() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("applications", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property applications18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property applications22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ark22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ark22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property back_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property best() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("best", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Best1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Best1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Best22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Best22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property billboard() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("billboard", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Boy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brick_house() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_house", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property bundle() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("bundle", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property buscar18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buscar18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buscar20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buscar20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buscar22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buscar22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property c_buscarD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c_buscarD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property c_buscarD18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c_buscarD18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property c_buscarI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c_buscarI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator22b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator22b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property catalogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("catalogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property catalogo16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("catalogo16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property catalogo2_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("catalogo2_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Catalogo24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Catalogo24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Catalogo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Catalogo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property catalogoLimpio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("catalogoLimpio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clien_list() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clien_list", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLOSE() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOSE", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property CLOSE18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOSE18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLOSE20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOSE20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLOSE22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOSE22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property continuar_a20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuar_a20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property continuar_a22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuar_a22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property continuar16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuar16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property continuar18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuar18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property continuar20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuar20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property continuar22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("continuar22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_panel() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("control_panel", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cubes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cubes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dolar_billete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dolar_billete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dollar20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dollar20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dollar22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dollar22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dollar28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dollar28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("down", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property down_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ejecutar22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ejecutar22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Error_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Error22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property estadisticas22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estadisticas22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Euro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Euro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FichaTecnica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FichaTecnica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FichaTecnica20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FichaTecnica20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FichaTecnica22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FichaTecnica22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter16_h() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("filter16_h", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property filter22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filtrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filtrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_find() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_find", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property folder_find18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_find18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_find22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_find22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo_021() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo_021", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo_verde_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo_verde_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fondo_verde_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo_verde_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_Empanaderia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_Empanaderia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_Empanaderia1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_Empanaderia1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_PRUSAC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_PRUSAC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_PRUSAC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_PRUSAC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_RNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_RNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_RNG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_RNG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_RosaNautica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_RosaNautica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_RosaNautica___copia___copia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_RosaNautica___copia___copia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fondo1024_RosaNautica1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo1024_RosaNautica1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ftp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ftp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property generar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property generar1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("generar1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property generar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property generar21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generar21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property herramientas22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("herramientas22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property History() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("History", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property history22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property important22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("important22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kardex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kardex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kardex1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kardex1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property List() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("List", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property lock_add() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lock_add", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property lock24() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lock24", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property loginsga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginsga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loginsge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginsge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_brecado_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_brecado_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_ficus_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_ficus_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_prusac_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_prusac_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_rnautica_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_rnautica_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoPrusacTrans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoPrusacTrans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logosga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logosga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGOSOS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGOSOS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logosss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logosss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logosss__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logosss__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_añadir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_añadir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_añadir18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_añadir18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_añadir20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_añadir20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_borrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_borrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_borrar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_borrar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_cancelar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_cancelar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_cancelar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_cancelar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_editar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_editar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_grabar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_grabar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_grabar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_grabar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_grabar20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_grabar20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MODPC07E22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MODPC07E22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Monedas22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monedas22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Monedas24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monedas24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monedas28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monedas28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nfs_mount22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nfs_mount22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Notas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property objects22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("objects22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Open18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Open2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Open2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Open20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Open21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Open24() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Open24", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ordenar_asc16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordenar_asc16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ordenar_asc22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordenar_asc22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ordenar_desc16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordenar_desc16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ordenar_desc22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ordenar_desc22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pass03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pass03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pass03_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pass03_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pdf22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pilot_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pilot_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pilot_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pilot_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PRINT() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PRINT", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property print_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_preview18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_preview18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_preview20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_preview20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property procedimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("procedimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property proveedor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proveedor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property punto01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punto01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property punto02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punto02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property punto03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punto03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property recetas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recetas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rendimiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rendimiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rendimiento22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rendimiento22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property retroceder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retroceder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rn1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("rn1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property rn16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("rn16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property rn22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rn22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rn24() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("rn24", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Rubik_Cube_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rubik_Cube_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rubik_Cube_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rubik_Cube_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SECUR05() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SECUR05", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SECUR05_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SECUR05_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SECUR05_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SECUR05_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sga128() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sga128", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property sga2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sga2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property sga48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sga48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart_full18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart_full18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart_full20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart_full20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart_full22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart_full22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart_full24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart_full24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property statistics2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("statistics2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property synaptic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("synaptic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property synaptic22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("synaptic22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tr() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Tr", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property tr_022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tr_022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tr_024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tr_024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transaction_logfile() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("transaction_logfile", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property transforma() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("transforma", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property transforma1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transforma1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transforma16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("transforma16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property transforma161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transforma161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Transformaciones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transformaciones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transporte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transporte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Undo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Undo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Undo_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Undo_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property up() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("up", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property up_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
